export enum QueryKey {
    'FORWARD_GEOCODING_BY_ADDRESS' = 'forwardGeocodingByAddress',
    'USER_GEOCODED_LOCATION' = 'userGeocodedLocation',
    'REVERSE_GEOCODING' = 'reverseGeocoding',
    'CALIBRATION' = 'calibration',
    'COMMUNITY_MUTATION' = 'community',
    'COMMUNITY_DELETE_MUTATION' = 'communityDelete',
    'PREDICTION' = 'prediction',
    'PREDICTION_BY_DAYS' = 'predictionByDays',
    'REGISTER_DETAILS' = 'registerDetails',
    'GOOGLE_LOGIN' = 'googleLogin',
    'COMMUNITIES' = 'communities',
    'COMMUNITY' = 'community',
    'POWER_PLANTS' = 'powerPlants',
    'POWER_PLANT' = 'powerPlant',
    'POWER_PLANT_UPDATE_MUTATION' = 'powerPlantUpdate',
    'POWER_PLANT_DELETE_MUTATION' = 'powerPlantDelete',
    'COMMUNITY_REMOVE_MEMBER_MUTATION' = 'communityRemoveMember',
}